# Generated by Django 3.2.9 on 2022-01-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('node_id', models.IntegerField(unique=True)),
                ('pm_value', models.FloatField()),
                ('t_value', models.FloatField()),
                ('h_value', models.FloatField()),
                ('p_value', models.FloatField()),
                ('v_value', models.FloatField()),
            ],
            options={
                'ordering': ['node_id', 'measured_at'],
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('location', models.CharField(help_text='Location of the node', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['user_id', 'node_id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(help_text='Password', max_length=50)),
                ('name', models.CharField(help_text='Name', max_length=50)),
                ('country', models.CharField(help_text='Country of origin', max_length=50)),
                ('mail', models.EmailField(help_text='Email', max_length=50)),
                ('phone', models.CharField(help_text='Phone', max_length=50)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
