# Generated by Django 3.2.9 on 2022-01-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogData',
            new_name='DataLog',
        ),
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
